//
// This file was generated by the Jeddict
//
package com.spingere.model;

import java.io.Serializable;

public class ClienteUsuarioPK implements Serializable {

    private static final long serialVersionUID = -9191376907646511074L;

    private int idCliente;

    private int idUsuario;

    private int idRolUsuario;

    public ClienteUsuarioPK() {
    }

    public ClienteUsuarioPK(int idCliente, int idUsuario, int idRolUsuario) {
        this.idCliente = idCliente;
        this.idUsuario = idUsuario;
        this.idRolUsuario = idRolUsuario;
    }

    public int getIdCliente() {
        return this.idCliente;
    }

    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    public int getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public int getIdRolUsuario() {
        return this.idRolUsuario;
    }

    public void setIdRolUsuario(int idRolUsuario) {
        this.idRolUsuario = idRolUsuario;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final ClienteUsuarioPK other = (ClienteUsuarioPK) obj;
        if (!java.util.Objects.equals(this.getIdCliente(), other.getIdCliente())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getIdUsuario(), other.getIdUsuario())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getIdRolUsuario(), other.getIdRolUsuario())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 73 * hash + this.getIdCliente();
        hash = 73 * hash + this.getIdUsuario();
        hash = 73 * hash + this.getIdRolUsuario();
        return hash;
    }

    @Override
    public String toString() {
        return "ClienteUsuarioPK{" + " idCliente=" + idCliente + ", idUsuario=" + idUsuario + ", idRolUsuario=" + idRolUsuario + '}';
    }

}